version: '3'
services:
    mysql-zabbix:
      container_name: mysql-zabbix
      build: ./DockerfileMysql
      command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=
        - MYSQL_ROOT_PASSWORD=
      networks:
        - zabbix-net
      restart: always

    zabbix-java-gateway:
      container_name: zabbix-java-gateway
      build: ./DockerfileZabbixJavaGw
      networks:
        - zabbix-net
      restart: always

    zabbix-server:
      container_name: zabbix-server
      build: ./DockerfileServer
      ports:
        - "10051:10051"
      environment:
        - ZBX_JAVAGATEWAY=zabbix-java-gateway
        - DB_SERVER_HOST=mysql-zabbix
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=
      networks:
        - zabbix-net
      depends_on:
        - mysql-zabbix
      restart: always
    
    zabbix-web:
      container_name: zabbix-web
      build: ./DockerfileZabbixWeb
      ports: 
        - "8010:8080"
      environment:
        - ZBX_SERVER_HOST=zabbix-server
        - DB_SERVER_HOST=mysql-zabbix
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=
        - PHP_TZ=America/Sao_Paulo
      networks:
        - zabbix-net
      depends_on:
        - mysql-zabbix
      restart: always

    phpmyadmin:
      container_name: myadmin
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
      networks:
        - zabbix-net
networks:
  zabbix-net:
    driver: bridge
    external: false